name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Загрузка исходного кода из вашего репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Настройка Java (JDK 17 необходимо для современных Android-проектов)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      # 3. Даем права на выполнение скрипту Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Сборка проекта (Debug APK)
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # 5. Сохранение готового APK файла как артефакта сборки
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
